In [1]:
import numpy as np

In [18]:
# in batched latent-data format
A = np.array([
    [1, 2, 3],
    [4, 5, 6], 
])

In [27]:
# calling reshape on batched latent-data preserves latent-data format
print(A)
print(A.reshape(6))
A_ld_vec = A.reshape(6)t

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [34]:
# since reshape preserves the format we can convert back to batched latent-data by reshaping
A_ld_vec.reshape([2, 3])

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# calling reshape on batched data-latent preserves data-latent format
print(A.T)
print((A.T).reshape(6))
A_dl_vec = (A.T).reshape(6)

[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [32]:
# since reshape preserves the format we can convert back to batched data-latent by reshaping
A_dl_vec.reshape([3, 2])

array([[1, 4],
       [2, 5],
       [3, 6]])