In [11]:
import numpy as np
import scipy as sp
import scipy.linalg

In [6]:
def random_matrix(N):
    return np.random.rand(N, N)

A_list = [
    random_matrix(2) for i in range(3)
]

In [7]:
np.A_list

[array([[0.05133968, 0.88732324],
        [0.72963035, 0.13305896]]),
 array([[0.28278274, 0.38994783],
        [0.60943307, 0.74374726]]),
 array([[0.80302028, 0.16427682],
        [0.81704218, 0.66852869]])]

In [15]:
truth = sp.linalg.block_diag(*A_list)
truth

array([[0.05133968, 0.88732324, 0.        , 0.        , 0.        ,
        0.        ],
       [0.72963035, 0.13305896, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.28278274, 0.38994783, 0.        ,
        0.        ],
       [0.        , 0.        , 0.60943307, 0.74374726, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.80302028,
        0.16427682],
       [0.        , 0.        , 0.        , 0.        , 0.81704218,
        0.66852869]])

In [17]:
np.np.vstack(A_list)
    

array([[0.05133968, 0.88732324],
       [0.72963035, 0.13305896],
       [0.28278274, 0.38994783],
       [0.60943307, 0.74374726],
       [0.80302028, 0.16427682],
       [0.81704218, 0.66852869]])